
## data("shapeData")
## data("pubExposed")
counts <- caseCounts()
pubExposed <- exposedPub()
## caseMap(counts, pubExposed)
historyCount <- countPlot(histoyCount, update = TRUE)
use_data(histoyCount)
report <- caseReport(counts, pubExposed, historyCount)
htmlwidgets::saveWidget(report, "index.html")
